### PR TITLE
test: add first fuzz testing code

### PR DESCRIPTION
**Pull request by quake**

### CODE REVIEW

**Comment by quake** [comment]
> Why need to create a separate crate for fuzzing? Can't write it directly in the test?

I just followed [tutorial](https://rust-fuzz.github.io/book/cargo-fuzz/setup.html), I suppose that it's best practice

**Comment by driftluo** [comment]
maybe add to ci ?

**Comment by doitian** [comment]
@quake could you add it to CI?

**Comment by quake** [comment]
> @quake could you add it to CI?

Fuzzing is endless, it will continue to run forever. Fuzzing is endless, not suitable for CI

**Comment by doitian** [comment]
> > @quake could you add it to CI?
> 
> Fuzzing is endless, it will continue to run forever. Fuzzing is endless, not suitable for CI

* https://github.com/rust-fuzz/cargo-fuzz/blob/ba40b1ac16309f99d9fc3bf8629f873340b864f5/src/main.rs#L63
* https://github.com/rust-fuzz/afl.rs/pull/162

**Pull request merged**
