### PR TITLE
Update to socket2 v0.4

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**

### CODE REVIEW

**Comment by driftluo** [comment]
@Thomasdezeeuw `socket2::Socket` convert to std, now need to use `Into::into`

**Comment by Thomasdezeeuw** [comment]
I missed some code paths, will fix.

**Review by driftluo — APPROVED** [review]

**Comment by Thomasdezeeuw** [comment]
The fuzzing failed, but I think that is unrelated to this change.

**Review by TheWaWaR — APPROVED** [review]

**Comment by driftluo** [comment]
> The fuzzing failed, but I think that is unrelated to this change.

yes, that's a test environment problem, thank you for your help

**Pull request merged**
